* 명명 패턴의 단점
  * 오타가 발생시 비정상 동작 할 수 있습니다.
  * 매개변수를 전달 할 마땅한 방법이 없습니다. 
* 이러한 단점을 개선하고자 애너테이션을 제공합니다. 
* 아래 `Test` 애너테이션으로 설명합니다.
```java
// 마커 애너테이션 타입 선언
import java.lang.annotation.*;

/**
 * 테스트 메서드임을 선언하는 애너테이션
 * 매개변수가 없는 정적 메서드 전용입니다
 */
// @Retention과 @Target는 애너테이션에 다는 메타 애너테이션입니다. 
// @Retention(RetentionPolicy.RUNTIME)는 런타임에서 유지되어야 한다는 뜻입니다. 
@Retention(RetentionPolicy.RUNTIME)
// @Target(ElementType.METHOD)는 메서드 선언 에서만 사용되어야 함을 뜻합니다. 
@Target(ElementType.METHOD)
public @interface Test{
}

// @Test는 매개변수 없이 마킹만 합니다. 그래서 마커 애너테이션이라고 합니다.

// 마커 애너테이션인 @Test를 사용한 예 
// @Test 애너테이션은 Sample 클래스에 직접적인 영향을 주지 않습니다. 다만 정보만 제공합니다. 
public class Sample {
    @Test
    public static void m1() {}
    public static void m2() {}
    @Test public static void m3() {
        throw new RuntimeException("실패");
    }
    public static void m4() {}
    @Test public void m5() {}   // 잘못 사용한 예 : 정적 메서드가 아닙니다. 
    public static void m6() {}
    @Test public static void m7() {
        throw new RuntimeException("실패");
    }
    public static void m8() {}
}

import java.lang.reflect.*;
public class RunTests {
    public static void main(String[] args) throws Exception {
        int tests = 0;
        int passed = 0;
        Class<?> testClass = Class.forName(args[0])
        // getDeclareMethods로 메서드의 클래스정보를 받아 올 수 있습니다. 
        for(Method m : testClass.getDeclareMethods()){
            // isAnnotationPresent로 애노테이션이 있는지 체크 할 수 있습니다. 
            if(m.isAnnotationPresent(Test.class)){
                tests++;
                try{
                    m.invoke(null);
                    passed++;
                // 테스트가 Exception을 던지면 reflect이 InvocationTargetException로 감싸서 던집니다. 
                }catch(InvocationTargetException wrappedExc){
                    Throwable exc = wrappedExc.getCause();
                    System.out.println(m + " 실패: " + exc);
                // InvocationTargetException 이외에 예외가 발생하면 @Test 애너테이션을 잘못 사용한 것입니다. 
                }catch(Exception exc){
                    System.out.println("잘못 사용한 @Test : " + m);
                }
            }
        }
        System.out.printf("성공 : %d 실패 : %d%n",
                        passed, tests - passed);
    }
}
```

* 특정 예외를 던저야지 성공하는 테스트를 지원하도록 구성해봅니다.
```java
import java.lang.annotation.*;

/**
 * 명시한 예외를 던져야만 성공하는 테스트 메서드용 애너테이션 
 */
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.METHOD)
public @interface ExceptionTest {
    Class<? extends Throwable> value();
}

// 매개변수 하나짜리 애너테이션을 사용한 예제
public class Sample2 {
    @ExceptionTest(ArithmeticException.class)
    public static void m1() {
        int i = 0;
        i = i / i;
    }

    @ExceptionTest(ArithmeticException.class)
    public static void m2() {
        int[] a = new int[0];
        int i = a[1];
    }

    @ExceptionTest(ArithmeticException.class)
    public static void m3() {}
}

import java.lang.reflect.*;
public class RunTests {
    public static void main(String[] args) throws Exception {
        // 생략..
            // isAnnotationPresent로 애노테이션이 있는지 체크 할 수 있습니다. 
            if(m.isAnnotationPresent(ExceptionTest.class)){
                tests++;
                try{
                    m.invoke(null);
                    System.out.println("테스트 %s 실패 : 예외를 던지지 않음", m);
                // 테스트가 Exception을 던지면 reflect이 InvocationTargetException로 감싸서 던집니다. 
                }catch(InvocationTargetException wrappedExc){
                    Throwable exc = wrappedExc.getCause();
                    // ExceptionTest의 value를 받아와서
                    Class<? extends Throwable> excType = 
                        m.getAnnotation(ExceptionTest.class).value();

                    // 발생한 예외와 비교합니다. 
                    if(excType.isInstance(exc)){
                        passed++;
                    } else {
                        System.out.printf(
                            "테스트 %s 실패: 기대한 예외 %s, 발생한 예외 %s%n",
                            m, excType.getName(), exc);
                    }
                // InvocationTargetException 이외에 예외가 발생하면 @Test 애너테이션을 잘못 사용한 것입니다. 
                }catch(Exception exc){
                    System.out.println("잘못 사용한 @Test : " + m);
                }
            }
        }
        // 생략..
    }
}
```
* 배열 매개변수를 받은 애너테이션용 문법
```java
@ExceptionTest({ IndexOutOfBoundsException.class, NullPointerException.class})
public static void doublyBad(){
    List<String> list = new ArrayList();
    // 자바 API 명세에 따르면 다음 메서드는 IndexOutOfBoundsException, NullPointerException를 던질 수 있습니다.
    list.add(5, null);
}

// 배열을 지원하도록 테스트 러너를 수정한 내용입니다.
if (m.isAnnotationPresent(ExceptionTest.class)) {
    test++;
    try{
        m.invoke(null);
        System.out.printf("테스트 %s 실패 : 예외를 던지지 않음%n", m);
    } catch( Throwable wrappedExc){
        Throwable exc = WrappedExc.getCause();
        int oldPassed = passed;
        Class<? extends Throwable> [] excTypes = 
            m.getAnnotation(ExceptionTest.class).value();
            for(Class<? extends Throwable> excType : excTypes){
                if(excType.isInstance(exc)) {
                    passed++;
                    break;
                }
            }
            if(passed == oldPassed)
                System.out.print("테스트 %s 실패 : %s %n", m, exc);
    }
}
```

* 자바 8에서는 여러개 값을 받는 애너테이션을 다른 방식으로 만들 수 있습니다.
  * `@Repeatable` 애너테이션을 다는 것입니다.
  * `@Repeatable` 사용시 주의 할 점
    * `@Repeatable` 애너테이션을 반환하는 컨테이너 애너테이션을 하나 더 정의하고 class 객체로 매개변수를 전달 해야 합니다.
    * 컨테이너 애너테이션은 내부 애너테이션 타입의 배열을 반환하는 value 메서드를 정의해야 합니다. 
```java
@Retrention(RetentionPolicy.RUNTIME)
@Target(ElementType.METHOD)
@Repeatable(ExceptionTestContainer.class)
public @interface ExcptionTest{
    Class<? extends Throwable> value();
}

// 컨테이너 애너테이션
@Retention(RetentionPolicy.RUNTIME)
@Terget(ElementType.METHON)
public @interface ExceptionTestContainer {
    ExceptionTest[] value();
}
```

